spring:
  application:
    name: ntseu_test_task_manager
  datasource:
    url: jdbc:h2:file:./data/task_manager;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      schema-locations: classpath:db/init_schema.sql
      data-locations: classpath:db/create_admin.sql
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080


jwt:
  secret-key: super-maxi-very-high-secret-key-SHA256
  expiration-ms: 24h

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs